package xiye.test.dao;

import java.util.List;
import xiye.test.model.Privilege;

public interface PrivilegeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_privilege
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_privilege
	 * @mbggenerated
	 */
	int insert(Privilege record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_privilege
	 * @mbggenerated
	 */
	Privilege selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_privilege
	 * @mbggenerated
	 */
	List<Privilege> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_privilege
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Privilege record);
}