package xiye.test.dao;

import java.util.List;
import xiye.test.model.RolePrivilege;

public interface RolePrivilegeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_privilege
	 * @mbggenerated
	 */
	int insert(RolePrivilege record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_privilege
	 * @mbggenerated
	 */
	List<RolePrivilege> selectAll();
}